# Generated by Django 5.0.6 on 2024-05-28 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerList',
            fields=[
                ('customer_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id of the customer')),
                ('customer_name', models.CharField(max_length=50, verbose_name='name of the customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('customer_id', models.OneToOneField(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='customers.customerlist')),
                ('customer_contact', models.CharField(max_length=13, verbose_name='mobile number of the customer')),
                ('customer_coordinates', models.CharField(max_length=100, verbose_name='location of the customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSearch',
            fields=[
                ('customer_id', models.OneToOneField(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='customers.customerlist')),
                ('customer_search', models.CharField(blank=True, verbose_name='search word history of the customer')),
            ],
        ),
    ]
