# Generated by Django 5.0.6 on 2024-07-23 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOTP',
            fields=[
                ('customer_id', models.OneToOneField(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='customers.customerlist')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
