# Generated by Django 5.0.6 on 2024-05-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendorList',
            fields=[
                ('vendor_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=30)),
            ],
        ),
    ]
