# Generated by Django 5.0.6 on 2024-05-28 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorDetails',
            fields=[
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vendors.vendorlist')),
                ('vendor_address', models.CharField(max_length=100)),
                ('vendor_dln', models.CharField(max_length=100, verbose_name="vendor's drug license number")),
                ('vendor_contact', models.CharField(max_length=14, verbose_name="vendor's contact number")),
                ('vendor_email', models.CharField(max_length=30, verbose_name="vendor's email address")),
                ('vendor_coordinates', models.CharField(max_length=100, verbose_name="vendor's geo-location co-ordinates(latitude, longitude)")),
            ],
        ),
    ]
