# Generated by Django 5.0.6 on 2024-05-28 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
        ('vendors', '0003_vendorcredentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorMedsSupply',
            fields=[
                ('vendor_id', models.OneToOneField(db_column='vendor_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vendors.vendorlist')),
                ('medicine_id', models.OneToOneField(db_column='medicine_id', on_delete=django.db.models.deletion.DO_NOTHING, to='medicines.medicinelist')),
            ],
        ),
    ]
