# Generated by Django 5.0.6 on 2024-05-31 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_vendormedssupply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendordetails',
            name='vendor_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vendors.vendorlist'),
        ),
    ]
