# Generated by Django 5.0.6 on 2024-07-12 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_alter_vendordetails_vendor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendormedssupply',
            old_name='medicine_id',
            new_name='medicine',
        ),
        migrations.RenameField(
            model_name='vendormedssupply',
            old_name='vendor_id',
            new_name='vendor',
        ),
    ]
