# Generated by Django 5.0.6 on 2024-05-28 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesList',
            fields=[
                ('category_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id of the respective category')),
                ('category_name', models.CharField(max_length=50, verbose_name='name of the category')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineCategory',
            fields=[
                ('medicine_id', models.OneToOneField(db_column='medicine_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='medicines.medicinelist')),
                ('category_id', models.OneToOneField(blank=True, db_column='category_id', on_delete=django.db.models.deletion.DO_NOTHING, to='medicines.categorieslist')),
            ],
        ),
    ]
